# Generated by Django 3.2.16 on 2023-02-08 18:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(verbose_name='Post date')),
                ('summary', wagtail.fields.RichTextField()),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('text_and_buttons', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock()), ('buttons', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock(label='Text', max_length=50, required=True)), ('button_link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True))]))), ('mainbutton', wagtail.blocks.StructBlock([('button_text', wagtail.blocks.CharBlock(label='Text', max_length=50, required=True)), ('button_link', wagtail.blocks.CharBlock(label='Link', max_length=255, required=True))]))]))], use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
