# Generated by Django 3.2.16 on 2023-02-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
